CREATE TABLE issues (
id_serial INT PRIMARY KEY,
id_jira VARCHAR(50) UNIQUE NOT NULL,
due_delivery DATE,
resolution VARCHAR(32),
desired_delivery DATE,
labels TEXT,
issuelinks TEXT,
assignee VARCHAR(80),
components VARCHAR(255),
sla_status VARCHAR(32),
clt_first_test DATE,
step VARCHAR(80),
subtasks VARCHAR(255),
pay_period_year VARCHAR(10),
reporter VARCHAR(80),
issuetype VARCHAR(32),
project VARCHAR(80),
group_assigment VARCHAR(10),
resolutiondate DATE,
watches INT,
ca_update VARCHAR(32),
updated DATE,
clt_priority_valid VARCHAR(10),
description TEXT,
declared_env VARCHAR(32),
nb_comments INT,
clt_priority VARCHAR(10),
expected_srh_end_date DATE,
summary TEXT,
due_date DATE,
last_assignee_srh VARCHAR(80),
main_closing_date DATE,
status VARCHAR(32),
creator VARCHAR(80),
main_delivery_date DATE,
timespent INT,
last_comment DATE,
created DATE,
mrgl_impact VARCHAR(32)
);